name: CICD Pipeline

# This workflow is triggered on push and pull request events to the develop and master branches.
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
  #Runs on latest windows version
    runs-on: self-hosted
    #checkouts on the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     #Sets up the latest version of .Net
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      #installs any dependencies
      - name: Restore dependencies
        run: dotnet restore
      #builds the application
      - name: Build application
        run: dotnet build --configuration Release --no-restore
      #Runs any available Unit/Integration tests
      - name: Run tests
        run: dotnet test --configuration Release --no-build

      #Publishes the Test application to a folder for deployment
      - name: Publish Test artifact
        if: github.ref == 'refs/heads/develop'
        run: dotnet publish --configuration Release --no-build --output ./publish-test
        env:
            ASPNETCORE_ENVIRONMENT: Test

      #uploads it after being published
      - name: Upload Test artifact
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v4
        with:
          name: test-app
          path: ./publish-test

      #Publishes the Test application to a folder for deployment
      - name: Publish Production artifact
        if: github.ref == 'refs/heads/master'
        run: dotnet publish --configuration Release --no-build --output ./publish-production
        env:
            ASPNETCORE_ENVIRONMENT: Production

      #uploads it after being published
      - name: Upload Production artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: production-app
          path: ./publish-production

      #Deploys to test directory
      - name: Deploy to Test
        if: github.ref == 'refs/heads/develop'
        run: |
          Stop-Service -Name "TestApp" -ErrorAction SilentlyContinue
          Copy-Item -Path ./publish-test/* -Destination "C:\deployments\test" -Recurse -Force
          Start-Service -Name "TestApp" -ErrorAction SilentlyContinue

      #Deploys to production directory
      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'
        run: |
          Stop-Service -Name "ProductionApp" -ErrorAction SilentlyContinue
          Copy-Item -Path ./publish-production/* -Destination "C:\deployments\production" -Recurse -Force
          Start-Service -Name "ProductionApp" -ErrorAction SilentlyContinue